Vagrant.require_version ">= 2.2.14"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    vms=[
      {
        :hostname => "jonas1",
        :box => "bento/ubuntu-20.04",
        :ip => "192.168.56.2",
        :ssh_port => '2222'
      }
    ]
    
    vms.each do |machine|
      config.vm.define machine[:hostname] do |node|
        node.vm.box = machine[:box]
        node.vm.hostname = machine[:hostname]
      
        node.vm.network :private_network, ip: machine[:ip]
        node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
 
        node.vm.provider :virtualbox do |v|
          v.customize ["modifyvm", :id, "--memory", 1024,"--cpus", 1]
          v.customize ["modifyvm", :id, "--name", machine[:hostname]]
        end
      end  
    end

end
